app = '83b-page'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  processes = ["app"]

[http_service.capabilities]
  sys_admin = true

[processes]
  app = "yarn start"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
